CI: Separate out cargo tests
Signed-off-by: Luis Garcia <git@luigi311.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,6 +12,33 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set rust
+        run: rustup update ${{ env.RUST_TOOLCHAIN }} && rustup default ${{ env.RUST_TOOLCHAIN }}
+
+      # Allow failure due to network blocks
+      - name: Cargo test
+        run: |
+          docker run -d \
+            --name=flaresolverr \
+            -p 8191:8191 \
+            -e LOG_LEVEL=info \
+            --restart unless-stopped \
+            --network=host \
+            ghcr.io/flaresolverr/flaresolverr:latest
+
+          # Sleep 5 seconds to wait for FlareSolverr to start
+          sleep 5
+
+          FLARESOLVERR_URL="http://localhost:8191/v1" cargo test -- --test-threads=1 || true
+
+          # Stop FlareSolverr
+          docker stop flaresolverr
+
   build:
     strategy:
       matrix:
@@ -34,26 +61,6 @@ jobs:
 
       - name: Set rust
         run: rustup update ${{ env.RUST_TOOLCHAIN }} && rustup default ${{ env.RUST_TOOLCHAIN }} && rustup target add ${{ matrix.platform.target }}
-
-      # Test only on linux once, allow failure due to network blocks
-      - name: Cargo test
-        if: ${{ matrix.platform.target == 'x86_64-unknown-linux-gnu' }}
-        run: |
-          docker run -d \
-            --name=flaresolverr \
-            -p 8191:8191 \
-            -e LOG_LEVEL=info \
-            --restart unless-stopped \
-            --network=host \
-            ghcr.io/flaresolverr/flaresolverr:latest
-
-          # Sleep 5 seconds to wait for FlareSolverr to start
-          sleep 5
-
-          FLARESOLVERR_URL="http://localhost:8191/v1" cargo test -- --test-threads=1 || true
-
-          # Stop FlareSolverr
-          docker stop flaresolverr
 
       - name: Cargo Build
         run: cargo build --release
